# Linux tasks
---
- name: Include tasks for Ubuntu systems
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Limit SSH connections
  community.general.ufw:
    rule: limit
    port: ssh

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
    system: yes
  tags: user

- name: Create {{ username }} user account
  ansible.builtin.user:
    name: "{{ username }}"
    comment: Jacob F. Grant
    home: "/home/{{ username }}"
    shell: /bin/bash
    groups:
      - docker
      - sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
  tags: user

- name: "{{ username }} actions"
  block:
    - name: Download SSH authorized_keys file
      ansible.builtin.get_url:
        url: https://gist.githubusercontent.com/jacobfgrant/40328a116c7fa215e01af4c4a63a5059/raw/authorized_keys
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        mode: 0644

    - name: Checkout dotfiles repository
      ansible.builtin.git:
        repo: https://github.com/jacobfgrant/dotfiles.git
        dest: "/home/{{ username }}/.dotfiles"
        force: yes
      register: update_dotfiles

    - name: Symlink dotfiles
      ansible.builtin.command:
        cmd: "sh /home/{{ username }}/.dotfiles/stow.sh"
        removes: "/home/{{ username }}/.dotfiles/stow.sh"
      when: update_dotfiles.changed
      ignore_errors: yes

    - name: Install Ansible
      ansible.builtin.pip:
        name:
          - ansible
          - ansible-lint
          - argcomplete
        state: latest
      tags: installs

  become: true
  become_user: "{{ username }}"
  tags: user

- name: Install Golang
  ansible.builtin.unarchive:
    src: "https://dl.google.com/go/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: /usr/local/
    owner: root
    group: root
    remote_src: yes
  when: golang_version is defined
  tags: installs
