# Main playbook file
---
- hosts: all
  vars:
  ## Package versions ##
    golang_version: 1.21.0
    slack_version: 4.33.90

  tasks:
    - name: Include tasks for Linux systems
      ansible.builtin.include_tasks: linux.yml
      when: ansible_facts['system'] == "Linux"
      vars:
        username: jfgrant
