# Main playbook file
---
- hosts: all
  vars:
  ## Package versions ##
    golang_version: 1.14.4
    packer_version: 1.6.0
    slack_version: 4.4.3
    terraform_version: 0.12.26
    vagrant_version: 2.2.9

  tasks:
  - name: Include tasks for Linux systems
    include_tasks: linux.yml
    when: ansible_facts['system'] == "Linux"
    vars:
      username: jfgrant
