# Main playbook file
---
- hosts: all
  vars:
  ## Package versions ##
    golang_version: 1.16.6
    slack_version: 4.18.0

  tasks:
  - name: Include tasks for Linux systems
    include_tasks: linux.yml
    when: ansible_facts['system'] == "Linux"
    vars:
      username: jfgrant
