# Ubuntu tasks
---
- name: Update/upgrade packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    state: latest
    install_recommends: true
    name:
      - aptitude
      - apt-transport-https
      - awscli
      - ca-certificates
      - curl
      - fail2ban
      - git
      - gnupg-agent
      - make
      - npm
      - python3
      - python3-pip
      - python3-venv
      - software-properties-common
      - stow
      - unrar
      - unzip
      - vim
      - wget
      - youtube-dl
      - zip
      - zsh
  tags: installs

- name: Install/configure Docker
  block:
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: installs

    - name: Add Docker repository (stable)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
        update_cache: true
      tags: installs

    - name: Install Docker packages
      ansible.builtin.apt:
        state: latest
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
          - docker-compose

  tags:
    - docker
    - installs

- name: Add Hashicorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  tags: installs

- name: Add Hashicorp repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts.distribution_release }} main"
    update_cache: true
  tags: installs

- name: Install Hashicorp packages
  ansible.builtin.apt:
    state: latest
    name:
      - packer
      - terraform
      - vault
  tags: installs

- name: Install GUI applications
  block:
    - name: Install Visual Studio Code
      ansible.builtin.apt:
        deb: https://go.microsoft.com/fwlink/?LinkID=760868

    - name: Install Google Chrome
      ansible.builtin.apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Install Slack
      ansible.builtin.apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb
      ignore_errors: true
      when: slack_version is defined

    - name: Install Discord
      ansible.builtin.apt:
        deb: https://discord.com/api/download?platform=linux&format=deb

    - name: Install GUI packages
      ansible.builtin.apt:
        state: latest
        install_recommends: true
        name:
          - gparted
          - keepassx

  when: "'DISPLAY' in ansible_env"
  tags:
    - gui
    - installs

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
