# .github/workflows/ansible-lint.yml
name: Ansible Lint

on:
  push:

  pull_request:
    branches:
      - master
      - dev

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Playbook
        uses: actions/checkout@v4

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@main
